# Generated by Django 3.0.4 on 2020-06-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craiglistscrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
